### ISSUE TITLE
entrypoint.sh should not chown DATADIR on mounted volumen

### ISSUE THREAD

**Issue by bySabi** [eea/eea.docker.scp-server#1]
Chowning DATADIR volumen should not be here.

**Comment by danijeljw** [comment]
Can you explain what you mean by this? I use this and I don't understand why you raised this issue. Can you provide some more context for me?

**Comment by bySabi** [comment]
@danijeljw It's been a long time since this. And I haven't played with Docker in a long time but it was probably because of this: https://stackoverflow.com/questions/39397548/how-to-give-non-root-user-in-docker-container-access-to-a-volume-mounted-on-the

I usually orchestrate the user ID with environment variables and **docker-compose**. Although I don't know the changes in Docker. I haven't touched it in a couple of years.
This is an example of a: `docker-compose.yml`

```
version: '3.6'
services:
  app-share:
    image: tianon/true
    volumes:
      - './app:/usr/src/app'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  scp:
    image: eeacms/scp-server
    environment:
      - DATADIR=/usr/src
      - 'AUTHORIZED_KEYS=${Scp_Authorized_keys}'
      - 'USERID=${Scp_userid}'
      - 'GROUPID=${Scp_groupid}'
    ports:
      - '2222:22'
    volumes_from:
      - app-share


```
